### ISSUE TITLE
Machines Spontaneously Breaking

### ISSUE THREAD

**Issue by AgentA1cr** [bdew/ae2stuff#168]
AE2stuff machines, specifically the advanced inscriber and crystal growth chamber, occasionally break spontaneously, particularly after returning from a long trip. Sometimes the blocks are dropped as an item, but do not drop their contents. Other times the item is not present, I assume because they despawn before I notice. 
Mod Version: 0.7.0.4
Forge Version: 14.23.1.2555

**Comment by thejims** [comment]
I'll second this, sounds like bug #131  ?  At least for me whenever I have an inscriber connected to a full block interface the inscriber breaks, losing it's contents completely, after reloading the chunk.  When connected to just the single facing interface and powering the inscriber via a quartz fiber the issue doesn't occur

**Comment by teufler80** [comment]
Yeah the bug is still present in 0.7.0.4. The machines break at chunk load and the acceleration upgrades and presser vanish.

**Comment by OrdinatorStouff** [comment]
Possibly related? https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3069

**Comment by lucasjones13** [comment]
I've done some testing and I believe that the machines popping off is caused by a conflict between security terminals and AE2Stuff. To prevent machines from popping off, hook them up with a quartz fiber rather than a cable alone - should fix this issue,

**Comment by jmac460** [comment]
I am having this exact same issue, except the chunks that they are in are loaded and they still drop.. Sometimes disappear completely or sometimes lose items... its getting annoying

**Comment by Morpheus1101** [comment]
I was having this exact same issue and found after moving my security terminal to not being on the same Cable/line that my Crafting, Pattern & Interface was on, solved the issue for me.

**Comment by princessbinas** [comment]
This is still occurring in the version used in SkyFactory 4 (rv6-stabvle-7). This is also happening with the ME Drives on the same version.

**Comment by jackyurchiksparrow** [comment]
It still happens in 1.12.2 0.7.04
